# Site Build Settings
url: "https://brazilianmonk.github.io"
baseurl: ""

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "brazilian monk"
# description:	       ""
author:              "Ariyañāṇa"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

google-ID: 'G-48EBF94R81'

collections:
  level_1:
    output: true
    permalink: /level-1/:name/
  level_2:
    output: true
    permalink: /level-2/:name/
  level_3:
    output: true
    permalink: /level-3/:name/

