# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-48EBF94R81'

menu:
- {name: 'Resources',  url: 'resources'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}
#- {name: 'Support',            url: 'support'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'youtube-play', link: 'http://www.youtube.com/@brazilian-monk'}
- {icon: 'facebook', link: 'https://www.facebook.com/share/16DspfKRGw/'}
- {icon: 'instagram', link: 'https://instagram.com/brazilian_monk'}
- {icon: 'archive', link: 'https://archive.org/details/@ariya_a_bhikkhu_stefano_domit_cervo_'}
- {icon: 'graduation-cap', link: 'https://independent.academia.edu/BrazilianMonkAriya%C3%B1%C4%81%E1%B9%87a'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}
- {icon: 'envelope', link: 'contact'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share'

related_posts: 'Related Posts'

post_date_prefix: 'written on'
